pipeline{
    agent{
        label 'ansible-label'
    }
    triggers{
        cron('0 0 1 * *')
       
    }
    stages{
        stage('run a cron every month'){
            steps{
                dir('/home/ec2-user/ansible-dev/cronjob'){
                    sh 'ansible-playbook cronplay.yml'
                }
            }
            
        }
    }

}
      