pipeline {
    agent {
        label 'agent-ansible'
    }
    stages {
        stage('Patching servers') {
            steps {
                dir('/home/ec2-user/ansible-dev/qafolder') {
                    sh 'ansible-playbook qa-playbook.yml'
                }
            }
        }
       /*  stage('Deploy application') {
            steps {
                dir('/home/ec2-user/pqa-stuff') {
                    sh 'ansible-playbook javaapp.yml'
                }
            }
        } */
    }
}